# ==========================================
# Tema Terrapunk / Paleta Tonal "Tinta Azul"
# ==========================================

# 1. Configuración Base (Papel y Tinta)
background            #E6DED5
foreground            #022164
cursor                #022164
cursor_text_color     #E6DED5
selection_background  #D4C9BC
selection_foreground  #010B22

# 2. Paleta Tonal ANSI (Variaciones estrictas de #022164)
# --------------------------------------------------------

# Negro (Texto general y comentarios)
# color0: Tinta Base | color8: Tinta Muy Lavada (para comentarios/gris ANSI)
color0  #022164
color8  #6C7AA0

# Rojo (Errores y Alertas Críticas)
# Mapeado a Tinta Pesada/Densa. Da un golpe visual fuerte sin salir del azul.
color1  #010B22
color9  #01153D

# Verde (Éxito y Cadenas de Texto)
# Mapeado a Tinta Lavada. Se lee bien pero no distrae la vista.
color2  #364D82
color10 #516491

# Amarillo (Advertencias)
# Mapeado a Tinta Intermedia Oscura. Llama la atención suavemente.
color3  #1C3773
color11 #364D82

# Azul (Palabras clave y Funciones)
# Mapeado a la Tinta Base.
color4  #022164
color12 #1C3773

# Magenta (Variables y Constantes)
# Mapeado a Tinta Intermedia.
color5  #364D82
color13 #516491

# Cyan (Tipos de datos y Rutas)
# Mapeado a Tinta Intermedia.
color6  #364D82
color14 #516491

# Blanco (Fondos y elementos de la interfaz TUI)
# Mapeado al color del Papel (#E6DED5) y Papel Mojado (#D4C9BC)
color7  #E6DED5
color15 #D4C9BC

# BEGIN_KITTY_FONT
font_family      Iosevka Nerd Font Mono
bold_font        Iosevka Nerd Font Mono Bold
italic_font      auto
bold_italic_font auto 
font_size        12.0
# END_KITTY_FONTS

window_padding_width 5
hide_window_decorations yes
modify_font cell_width 115%


