ln -sf ~/.config/dotfiles/kitty/kitty.conf ~/.config/kitty/kitty.conf
ln -sf ~/.config/dotfiles/bat/bat_config ~/.config/bat/config
ln -sf ~/.config/dotfiles/helix/helix_blueink.toml ~/.config/helix/themes/blueink.toml
ln -sf ~/.config/dotfiles/micro/micro_blueink.micro ~/.config/micro/colorschemes/blueink.micro
ln -sf ~/.config/dotfiles/micro/micro_settings.json ~/.config/micro/settings.json
ln -sf ~/.config/dotfiles/btop/btop_blueink.theme ~/.config/btop/themes/blueink.theme
ln -sf ~/.config/dotfiles/niri ~/.config/niri
ln -sf ~/.config/dotfiles/yazi ~/.config/yazi
ln -sf ~/.config/dotfiles/waybar ~/.config/waybar
ln -sf ~/.config/dotfiles/fuzzel ~/.config/fuzzel
ln -s ~/.config/dotfiles/qutebrowser ~/.config/qutebrowser
ln -sf ~/.config/dotfiles/mako ~/.config/mako
ln -sf ~/.config/dotfiles/zathura ~/.config/zathura
